app: aws-golang-rest-api-with-dynamodb
service: aws-golang-rest-api-with-dynamodb

frameworkVersion: ">=2.24.0"

provider:
  name: aws
  runtime: go1.x
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  create:
    handler: bin/create
    package:
      include:
        - ./bin/create
    events:
      - http:
          path: notes
          method: post
          cors: true

  list:
    handler: bin/list
    package:
      include:
        - ./bin/list
    events:
      - http:
          path: notes
          method: get
          cors: true

  get:
    handler: bin/get
    package:
      include:
        - ./bin/get
    events:
      - http:
          path: notes/{id}
          method: get
          cors: true

  update:
    handler: bin/update
    package:
      include:
        - ./bin/update
    events:
      - http:
          path: notes/{id}
          method: put
          cors: true

  delete:
    handler: bin/delete
    package:
      include:
        - ./bin/deleteBin
    events:
      - http:
          path: notes/{id}
          method: delete
          cors: true

resources:
  Resources:
    TodosDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
